
project_id = "ymkzgfglgqivuzetsplg"

[api]
enabled = true
url = "https://ymkzgfglgqivuzetsplg.supabase.co"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlta3pnZmdsZ3FpdnV6ZXRzcGxnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczOTYzMTY3NCwiZXhwIjoyMDU1MjA3Njc0fQ.bGmyT3Bamzx6PQyuDX3GQbWMNmLQGWtomf87IfMDSd0"

[functions]
serve = true
