// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymkzgfglgqivuzetsplg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlta3pnZmdsZ3FpdnV6ZXRzcGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MzE2NzQsImV4cCI6MjA1NTIwNzY3NH0.pbYkeq0ypF0G7KX0cWEarLVrhHGkiF-8VsbjmldCXWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);